# name: Generate Snake

# on:
#   schedule:
#     - cron: "0 */6 * * *"
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2

#       - uses: Platane/snk@master
#         id: snake-gif
#         with:
#           github_user_name: vartikasinghp  # 👈 Replace this with your GitHub username
#           gif_out_path: dist/github-contribution-grid-snake.gif
#           svg_out_path: dist/github-contribution-grid-snake.svg

#       - name: Push Snake files to output branch
#         uses: crazy-max/ghaction-github-pages@v2.1.3
#         with:
#           target_branch: output
#           build_dir: dist
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# GitHub Action for generating a contribution graph with a snake eating your contributions.
name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC
  workflow_dispatch: # Allows you to trigger manually from Actions tab

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: vartikasinghp
          outputs: |
            dist/github-contribution-grid-snake-dark.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

